# Generated by Django 6.0.5 on 2026-05-08 16:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('plaid', 'Plaid')], default='plaid', max_length=32)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('logo', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('plaid', 'Plaid')], default='plaid', max_length=32)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('requires_attention', 'Requires attention'), ('removed', 'Removed')], default='active', max_length=32)),
                ('sync_cursor', models.TextField(blank=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_webhook_code', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_items', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_items', to='core.institution')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255)),
                ('mask', models.CharField(blank=True, max_length=8)),
                ('type', models.CharField(max_length=64)),
                ('subtype', models.CharField(blank=True, max_length=64)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.connecteditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='core.institution')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('plaid', 'Plaid')], default='plaid', max_length=32)),
                ('loan_type', models.CharField(blank=True, max_length=64)),
                ('lender_name', models.CharField(blank=True, max_length=255)),
                ('account_number_mask', models.CharField(blank=True, max_length=8)),
                ('interest_rate_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('originating_principal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_statement_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minimum_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_payment_due_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_liability', to='core.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('initial', 'Initial'), ('manual', 'Manual'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook')], max_length=32)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='started', max_length=32)),
                ('accounts_seen', models.PositiveIntegerField(default=0)),
                ('transactions_added', models.PositiveIntegerField(default=0)),
                ('transactions_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='core.connecteditem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('pending_transaction_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iso_currency_code', models.CharField(default='USD', max_length=3)),
                ('date', models.DateField()),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('category', models.JSONField(blank=True, default=list)),
                ('pending', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.financialaccount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.connecteditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
    ]
