# Generated by Django 6.0.5 on 2026-05-11 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_linked_merchant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount per payment', max_digits=12)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('semimonthly', 'Semi-monthly (1st & 15th)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One-time')], default='monthly', max_length=32)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('bonus', 'Bonus'), ('freelance', 'Freelance / Contract'), ('investment', 'Investment / Dividends'), ('rental', 'Rental Income'), ('other', 'Other')], default='salary', max_length=32)),
                ('next_pay_date', models.DateField(blank=True, help_text='Anchor date for bi-weekly/weekly; expected date for quarterly/annual/one-time', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1–28) for monthly income', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount', 'name'],
            },
        ),
    ]
