# Generated by Django 6.0.5 on 2026-05-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_variable_expense_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='linked_merchant',
            field=models.CharField(blank=True, help_text='Merchant/payer name pattern to auto-match against imported transactions', max_length=255),
        ),
    ]
