# Generated by Django 6.0.5 on 2026-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_income_linked_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='linked_merchant',
            field=models.TextField(blank=True, help_text='Merchant name pattern to auto-match against imported transactions'),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='linked_merchant',
            field=models.TextField(blank=True, help_text='Merchant/payer name pattern to auto-match against imported transactions'),
        ),
    ]
