# Generated by Django 6.0.5 on 2026-05-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_linked_merchant_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_key', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['merchant_key'],
            },
        ),
    ]
