# Generated by Django 6.0.5 on 2026-05-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_transfer_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('housing', 'Housing'), ('utilities', 'Utilities'), ('groceries', 'Groceries'), ('dining', 'Dining & Bars'), ('transport', 'Transportation'), ('health', 'Health & Fitness'), ('insurance', 'Insurance'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('subscriptions', 'Subscriptions'), ('education', 'Education & Childcare'), ('personal', 'Personal Care'), ('pets', 'Pets'), ('debt', 'Debt Payments'), ('savings', 'Savings & Investment'), ('taxes', 'Taxes & Fees'), ('other', 'Other')], default='other', max_length=64),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('semimonthly', 'Semi-monthly (1st & 15th)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One-time'), ('variable', 'Variable')], default='monthly', max_length=32),
        ),
    ]
